# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
os:
  - osx
  - linux
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages

git:
  depth: 3
  
script:
  - R CMD build .
  - R CMD check *tar.gz
